Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: main
      CodeUri: /home/andrii/GolandProjects/confluence-rest-golang
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          CONF_LOC_U: admin
          CONF_LOC_P: admin